### ISSUE TITLE
Support for secrets using KMS?

### ISSUE THREAD

**Issue by noah-goodrich** [LeoPlatform/Nodejs#14]
As part of a deployment strategy, it is vital that secrets (think db passwords, api tokens, etc) are not stored directly in code. It would appear that the accepted solution in AWS is to use Key Management Service to safely store those secrets encrypted by KMS and then pass around the Master Key in your config files and such.

Does the leo-sdk support working with KMS out of the box? If so, how do I setup values into KMS for consumption in a leo bot and then access those values in the actual bot?

**Comment by Handyman** [comment]
I wrote up a quick example for this here: https://github.com/LeoPlatform/cli/wiki/FAQ

**Comment by Handyman** [comment]
This is done with the implementation of secrets manager now in leo-aws. We just need to document it.
```require('leo-aws').secrets.getSecret('secretName');```
