### ISSUE TITLE
Promises! Promises! Promises!

### ISSUE THREAD

**Issue by noah-goodrich** [LeoPlatform/Nodejs#15]
The aws-sdk for nodejs has supported promises natively for some time now using this style syntax:

`s3.putObject(params).promise();`

It would be extremely useful if we could use leo-sdk the same way:

`leo.load(params).promise();`

And

`leo.offload(params).promise()`

**Comment by noah-goodrich** [comment]
I see that this hasn't received a response yet. I just wanted to followup now that node v8 is available as a runtime in AWS Lambda now and `async/await` is now available.

After a great deal of time spent reading to try and fully understand the callback, promise, generator conversation, I can very confidently state that Promises from the Leo sdk are a must-have given that `async/await` just returns / consumes promises.

I recently worked on a new bot using the Leo sdk and converted a single function to be promise compatible: 

```
const sqlServer = require("leo-connector-sqlserver").connect(config.sql_server);

const query = (query, params, opts = {}) => {
  return new Promise((resolve, reject) => {
    sqlServer.query(query, params, (err,data) => {
      if(err) reject(err);

      resolve(data);
    }, opts);
  });
};
```

Please note that if this function were written in such way that it took the callback as the last param instead of the `opts` object, I could have replace the above with this:

```
const query = Util.promisify(sqlServer.query);
```

What would it take to at least get all of your callback functions fully compatible with the `Util.promisify` requirement that the callback always be the last argument?

From there, it should be pretty small to return a promisified version of each library.

**Comment by roaringdev** [comment]
We just upgraded our leo-cli to publish to the new NodeJS8.10 that lambda supports.  With this our goal is to start supporting promises and async/await better. 

we will begin working on promisifying the major APIs shortly.

**Comment by roaringdev** [comment]
We have moved our aws libraries to leo-aws with full promise support.

We are currently moving more utility libraries into their own systems.

**Comment by Handyman** [comment]
Closing this since it isn't a specific issue but more of a suggestion to move in a direction. We are actively cleaning up and moving in the direction of promisifying, and it will take time. If you have any specific improvements, please feel free to open pull requests in any of the repositories and we can get those changes merged and published.
